2012-06-25 11:59:42,121 BaseClientAuditController DEBUG   dumping options
2012-06-25 11:59:42,121 BaseClientAuditController DEBUG   	self_test = 0
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	nclients = 1
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	user_ca_cert_file = txjsonrpc-test-ca-cacert.pem
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	user_ca_key_file = cacert.key
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	gui = False
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	no_self_signed = False
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	modules = sslcert
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	quiet = False
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	server = ('localhost', 7443)
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	debug_level = 0
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	no_default_cn = False
2012-06-25 11:59:42,122 BaseClientAuditController DEBUG   	no_user_cert_signed = False
2012-06-25 11:59:42,123 BaseClientAuditController DEBUG   	user_cert_file = None
2012-06-25 11:59:42,123 BaseClientAuditController DEBUG   	test_name = None
2012-06-25 11:59:42,123 BaseClientAuditController DEBUG   	user_key_file = None
2012-06-25 11:59:42,123 BaseClientAuditController DEBUG   	user_cn = None
2012-06-25 11:59:42,123 BaseClientAuditController DEBUG   	listen_on = ('0.0.0.0', 8443)
2012-06-25 11:59:42,123 BaseClientAuditController DEBUG   	protocols = None
2012-06-25 11:59:42,123 BaseClientAuditController DEBUG   end of options dump
2012-06-25 11:59:42,123 BaseClientAuditController INFO   number of profile factories: 1
2012-06-25 11:59:42,123 BaseClientAuditController INFO   profile factory: SSLCert (10 profiles)
2012-06-25 11:59:42,123 SSLCAuditCLI INFO   filebag location: sslcaudit.3
2012-06-25 11:59:42,124 ClientAuditorTCPServer INFO   listen_on: ('0.0.0.0', 8443)
2012-06-25 11:59:42,124 BaseClientAuditController DEBUG   entering main loop in run()
2012-06-25 11:59:42,208 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:42,209 ClientAuditorTCPServer DEBUG   new session [id 127.0.0.1]
2012-06-25 11:59:42,209 ClientServerSessionHandler DEBUG   will use profile 0 to handle connection 127.0.0.1 [('127.0.0.1', 47752)->('127.0.0.1', 8443)]
2012-06-25 11:59:42,209 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47752)->('127.0.0.1', 8443)] with profile selfsigned(www.example.com)[tmpmEfPBC-cert.pem]
2012-06-25 11:59:42,211 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:42,212 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47752)->('127.0.0.1', 8443)] using selfsigned(www.example.com)[tmpmEfPBC-cert.pem] (0/10) resulted in ConnectionAuditResult(selfsigned(www.example.com)[tmpmEfPBC-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:42,224 BaseClientAuditController DEBUG   got result <sslcaudit.core.ConnectionAuditEvent.SessionStartEvent object at 0x2e33290>
2012-06-25 11:59:42,225 BaseClientAuditController DEBUG   got result ConnectionAuditResult(selfsigned(www.example.com)[tmpmEfPBC-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:42,511 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:42,511 ClientServerSessionHandler DEBUG   will use profile 1 to handle connection 127.0.0.1 [('127.0.0.1', 47753)->('127.0.0.1', 8443)]
2012-06-25 11:59:42,513 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47753)->('127.0.0.1', 8443)] with profile selfsigned(txjsonrpc-pyserver)[tmp7OsdbU-cert.pem]
2012-06-25 11:59:42,516 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:42,516 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47753)->('127.0.0.1', 8443)] using selfsigned(txjsonrpc-pyserver)[tmp7OsdbU-cert.pem] (1/10) resulted in ConnectionAuditResult(selfsigned(txjsonrpc-pyserver)[tmp7OsdbU-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:42,526 BaseClientAuditController DEBUG   got result ConnectionAuditResult(selfsigned(txjsonrpc-pyserver)[tmp7OsdbU-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:42,808 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:42,808 ClientServerSessionHandler DEBUG   will use profile 2 to handle connection 127.0.0.1 [('127.0.0.1', 47754)->('127.0.0.1', 8443)]
2012-06-25 11:59:42,809 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47754)->('127.0.0.1', 8443)] with profile signed1(www.example.com, txjsonrpc-test-ca)[tmpaJ8Mp6-cert.pem]
2012-06-25 11:59:42,814 SSLServerHandler DEBUG   SSL connection accepted, version TLSv1, cipher AES256-SHA-256
2012-06-25 11:59:42,816 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47754)->('127.0.0.1', 8443)] using signed1(www.example.com, txjsonrpc-test-ca)[tmpaJ8Mp6-cert.pem] (2/10) resulted in ConnectionAuditResult(signed1(www.example.com, txjsonrpc-test-ca)[tmpaJ8Mp6-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:42,827 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed1(www.example.com, txjsonrpc-test-ca)[tmpaJ8Mp6-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:43,108 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:43,108 ClientServerSessionHandler DEBUG   will use profile 3 to handle connection 127.0.0.1 [('127.0.0.1', 47755)->('127.0.0.1', 8443)]
2012-06-25 11:59:43,109 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47755)->('127.0.0.1', 8443)] with profile signed1(txjsonrpc-pyserver, txjsonrpc-test-ca)[tmpuwDL0h-cert.pem]
2012-06-25 11:59:43,143 SSLServerHandler DEBUG   SSL connection accepted, version TLSv1, cipher AES256-SHA-256
2012-06-25 11:59:43,144 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47755)->('127.0.0.1', 8443)] using signed1(txjsonrpc-pyserver, txjsonrpc-test-ca)[tmpuwDL0h-cert.pem] (3/10) resulted in ConnectionAuditResult(signed1(txjsonrpc-pyserver, txjsonrpc-test-ca)[tmpuwDL0h-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:43,160 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed1(txjsonrpc-pyserver, txjsonrpc-test-ca)[tmpuwDL0h-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:43,445 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:43,445 ClientServerSessionHandler DEBUG   will use profile 4 to handle connection 127.0.0.1 [('127.0.0.1', 47756)->('127.0.0.1', 8443)]
2012-06-25 11:59:43,446 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47756)->('127.0.0.1', 8443)] with profile signed2(www.example.com, ca-none, txjsonrpc-test-ca)[tmpo6KFyt-cert.pem]
2012-06-25 11:59:43,448 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:43,448 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47756)->('127.0.0.1', 8443)] using signed2(www.example.com, ca-none, txjsonrpc-test-ca)[tmpo6KFyt-cert.pem] (4/10) resulted in ConnectionAuditResult(signed2(www.example.com, ca-none, txjsonrpc-test-ca)[tmpo6KFyt-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:43,460 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(www.example.com, ca-none, txjsonrpc-test-ca)[tmpo6KFyt-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:43,747 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:43,747 ClientServerSessionHandler DEBUG   will use profile 5 to handle connection 127.0.0.1 [('127.0.0.1', 47757)->('127.0.0.1', 8443)]
2012-06-25 11:59:43,747 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47757)->('127.0.0.1', 8443)] with profile signed2(www.example.com, ca-false, txjsonrpc-test-ca)[tmp4lfgn6-cert.pem]
2012-06-25 11:59:43,751 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:43,751 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47757)->('127.0.0.1', 8443)] using signed2(www.example.com, ca-false, txjsonrpc-test-ca)[tmp4lfgn6-cert.pem] (5/10) resulted in ConnectionAuditResult(signed2(www.example.com, ca-false, txjsonrpc-test-ca)[tmp4lfgn6-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:43,761 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(www.example.com, ca-false, txjsonrpc-test-ca)[tmp4lfgn6-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:44,045 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:44,045 ClientServerSessionHandler DEBUG   will use profile 6 to handle connection 127.0.0.1 [('127.0.0.1', 47758)->('127.0.0.1', 8443)]
2012-06-25 11:59:44,046 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47758)->('127.0.0.1', 8443)] with profile signed2(www.example.com, ca-true, txjsonrpc-test-ca)[tmpLcuhFJ-cert.pem]
2012-06-25 11:59:44,052 SSLServerHandler DEBUG   SSL connection accepted, version TLSv1, cipher AES256-SHA-256
2012-06-25 11:59:44,054 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47758)->('127.0.0.1', 8443)] using signed2(www.example.com, ca-true, txjsonrpc-test-ca)[tmpLcuhFJ-cert.pem] (6/10) resulted in ConnectionAuditResult(signed2(www.example.com, ca-true, txjsonrpc-test-ca)[tmpLcuhFJ-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:44,062 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(www.example.com, ca-true, txjsonrpc-test-ca)[tmpLcuhFJ-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:44,356 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:44,356 ClientServerSessionHandler DEBUG   will use profile 7 to handle connection 127.0.0.1 [('127.0.0.1', 47759)->('127.0.0.1', 8443)]
2012-06-25 11:59:44,357 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47759)->('127.0.0.1', 8443)] with profile signed2(txjsonrpc-pyserver, ca-none, txjsonrpc-test-ca)[tmpuQYxIz-cert.pem]
2012-06-25 11:59:44,359 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:44,359 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47759)->('127.0.0.1', 8443)] using signed2(txjsonrpc-pyserver, ca-none, txjsonrpc-test-ca)[tmpuQYxIz-cert.pem] (7/10) resulted in ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-none, txjsonrpc-test-ca)[tmpuQYxIz-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:44,363 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-none, txjsonrpc-test-ca)[tmpuQYxIz-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:44,660 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:44,660 ClientServerSessionHandler DEBUG   will use profile 8 to handle connection 127.0.0.1 [('127.0.0.1', 47760)->('127.0.0.1', 8443)]
2012-06-25 11:59:44,661 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47760)->('127.0.0.1', 8443)] with profile signed2(txjsonrpc-pyserver, ca-false, txjsonrpc-test-ca)[tmp90NtYZ-cert.pem]
2012-06-25 11:59:44,662 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:44,662 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47760)->('127.0.0.1', 8443)] using signed2(txjsonrpc-pyserver, ca-false, txjsonrpc-test-ca)[tmp90NtYZ-cert.pem] (8/10) resulted in ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-false, txjsonrpc-test-ca)[tmp90NtYZ-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:44,664 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-false, txjsonrpc-test-ca)[tmp90NtYZ-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:44,959 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:44,959 ClientServerSessionHandler DEBUG   will use profile 9 to handle connection 127.0.0.1 [('127.0.0.1', 47761)->('127.0.0.1', 8443)]
2012-06-25 11:59:44,960 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47761)->('127.0.0.1', 8443)] with profile signed2(txjsonrpc-pyserver, ca-true, txjsonrpc-test-ca)[tmp9uWipi-cert.pem]
2012-06-25 11:59:44,964 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:44,965 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47761)->('127.0.0.1', 8443)] using signed2(txjsonrpc-pyserver, ca-true, txjsonrpc-test-ca)[tmp9uWipi-cert.pem] (9/10) resulted in ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-true, txjsonrpc-test-ca)[tmp9uWipi-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:44,965 ClientServerSessionHandler DEBUG   last profile for connection 127.0.0.1 [('127.0.0.1', 47761)->('127.0.0.1', 8443)]
2012-06-25 11:59:44,966 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-true, txjsonrpc-test-ca)[tmp9uWipi-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:44,967 BaseClientAuditController DEBUG   got result <sslcaudit.core.ConnectionAuditEvent.SessionEndResult object at 0x2e33310>
2012-06-25 11:59:45,260 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:45,260 ClientServerSessionHandler DEBUG   no unused profiles for connection 127.0.0.1 [('127.0.0.1', 47762)->('127.0.0.1', 8443)], invoking the posttest handler
2012-06-25 11:59:45,261 BaseClientAuditController DEBUG   exited main loop in run()
