2012-06-25 11:59:54,284 BaseClientAuditController DEBUG   dumping options
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	self_test = 0
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	nclients = 1
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	user_ca_cert_file = txjsonrpc-test-ca-cacert.pem
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	user_ca_key_file = cacert.key
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	gui = False
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	no_self_signed = False
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	modules = sslcert
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	quiet = False
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	server = ('localhost', 7443)
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	debug_level = 0
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	no_default_cn = False
2012-06-25 11:59:54,285 BaseClientAuditController DEBUG   	no_user_cert_signed = False
2012-06-25 11:59:54,286 BaseClientAuditController DEBUG   	user_cert_file = None
2012-06-25 11:59:54,286 BaseClientAuditController DEBUG   	test_name = None
2012-06-25 11:59:54,286 BaseClientAuditController DEBUG   	user_key_file = None
2012-06-25 11:59:54,286 BaseClientAuditController DEBUG   	user_cn = None
2012-06-25 11:59:54,286 BaseClientAuditController DEBUG   	listen_on = ('0.0.0.0', 8443)
2012-06-25 11:59:54,286 BaseClientAuditController DEBUG   	protocols = None
2012-06-25 11:59:54,286 BaseClientAuditController DEBUG   end of options dump
2012-06-25 11:59:54,286 BaseClientAuditController INFO   number of profile factories: 1
2012-06-25 11:59:54,286 BaseClientAuditController INFO   profile factory: SSLCert (10 profiles)
2012-06-25 11:59:54,287 SSLCAuditCLI INFO   filebag location: sslcaudit.4
2012-06-25 11:59:54,287 ClientAuditorTCPServer INFO   listen_on: ('0.0.0.0', 8443)
2012-06-25 11:59:54,287 BaseClientAuditController DEBUG   entering main loop in run()
2012-06-25 11:59:54,502 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:54,503 ClientAuditorTCPServer DEBUG   new session [id 127.0.0.1]
2012-06-25 11:59:54,503 ClientServerSessionHandler DEBUG   will use profile 0 to handle connection 127.0.0.1 [('127.0.0.1', 47794)->('127.0.0.1', 8443)]
2012-06-25 11:59:54,504 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47794)->('127.0.0.1', 8443)] with profile selfsigned(www.example.com)[tmpN_7qXh-cert.pem]
2012-06-25 11:59:54,504 BaseClientAuditController DEBUG   got result <sslcaudit.core.ConnectionAuditEvent.SessionStartEvent object at 0x1376290>
2012-06-25 11:59:54,507 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:54,507 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47794)->('127.0.0.1', 8443)] using selfsigned(www.example.com)[tmpN_7qXh-cert.pem] (0/10) resulted in ConnectionAuditResult(selfsigned(www.example.com)[tmpN_7qXh-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:54,508 BaseClientAuditController DEBUG   got result ConnectionAuditResult(selfsigned(www.example.com)[tmpN_7qXh-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:54,800 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:54,800 ClientServerSessionHandler DEBUG   will use profile 1 to handle connection 127.0.0.1 [('127.0.0.1', 47795)->('127.0.0.1', 8443)]
2012-06-25 11:59:54,801 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47795)->('127.0.0.1', 8443)] with profile selfsigned(txjsonrpc-pyserver)[tmpMDe4ab-cert.pem]
2012-06-25 11:59:54,803 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:54,804 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47795)->('127.0.0.1', 8443)] using selfsigned(txjsonrpc-pyserver)[tmpMDe4ab-cert.pem] (1/10) resulted in ConnectionAuditResult(selfsigned(txjsonrpc-pyserver)[tmpMDe4ab-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:54,809 BaseClientAuditController DEBUG   got result ConnectionAuditResult(selfsigned(txjsonrpc-pyserver)[tmpMDe4ab-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:55,098 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:55,098 ClientServerSessionHandler DEBUG   will use profile 2 to handle connection 127.0.0.1 [('127.0.0.1', 47796)->('127.0.0.1', 8443)]
2012-06-25 11:59:55,099 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47796)->('127.0.0.1', 8443)] with profile signed1(www.example.com, txjsonrpc-test-ca)[tmp8ahLZ0-cert.pem]
2012-06-25 11:59:55,107 SSLServerHandler DEBUG   SSL connection accepted, version TLSv1, cipher AES256-SHA-256
2012-06-25 11:59:55,109 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47796)->('127.0.0.1', 8443)] using signed1(www.example.com, txjsonrpc-test-ca)[tmp8ahLZ0-cert.pem] (2/10) resulted in ConnectionAuditResult(signed1(www.example.com, txjsonrpc-test-ca)[tmp8ahLZ0-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:55,110 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed1(www.example.com, txjsonrpc-test-ca)[tmp8ahLZ0-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:55,410 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:55,411 ClientServerSessionHandler DEBUG   will use profile 3 to handle connection 127.0.0.1 [('127.0.0.1', 47797)->('127.0.0.1', 8443)]
2012-06-25 11:59:55,412 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47797)->('127.0.0.1', 8443)] with profile signed1(txjsonrpc-pyserver, txjsonrpc-test-ca)[tmpyaxJPv-cert.pem]
2012-06-25 11:59:55,449 SSLServerHandler DEBUG   SSL connection accepted, version TLSv1, cipher AES256-SHA-256
2012-06-25 11:59:55,451 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47797)->('127.0.0.1', 8443)] using signed1(txjsonrpc-pyserver, txjsonrpc-test-ca)[tmpyaxJPv-cert.pem] (3/10) resulted in ConnectionAuditResult(signed1(txjsonrpc-pyserver, txjsonrpc-test-ca)[tmpyaxJPv-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:55,476 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed1(txjsonrpc-pyserver, txjsonrpc-test-ca)[tmpyaxJPv-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:55,749 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:55,750 ClientServerSessionHandler DEBUG   will use profile 4 to handle connection 127.0.0.1 [('127.0.0.1', 47798)->('127.0.0.1', 8443)]
2012-06-25 11:59:55,750 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47798)->('127.0.0.1', 8443)] with profile signed2(www.example.com, ca-none, txjsonrpc-test-ca)[tmp9WZP8g-cert.pem]
2012-06-25 11:59:55,753 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:55,753 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47798)->('127.0.0.1', 8443)] using signed2(www.example.com, ca-none, txjsonrpc-test-ca)[tmp9WZP8g-cert.pem] (4/10) resulted in ConnectionAuditResult(signed2(www.example.com, ca-none, txjsonrpc-test-ca)[tmp9WZP8g-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:55,777 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(www.example.com, ca-none, txjsonrpc-test-ca)[tmp9WZP8g-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:56,049 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:56,050 ClientServerSessionHandler DEBUG   will use profile 5 to handle connection 127.0.0.1 [('127.0.0.1', 47799)->('127.0.0.1', 8443)]
2012-06-25 11:59:56,051 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47799)->('127.0.0.1', 8443)] with profile signed2(www.example.com, ca-false, txjsonrpc-test-ca)[tmpkOWcDc-cert.pem]
2012-06-25 11:59:56,054 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:56,054 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47799)->('127.0.0.1', 8443)] using signed2(www.example.com, ca-false, txjsonrpc-test-ca)[tmpkOWcDc-cert.pem] (5/10) resulted in ConnectionAuditResult(signed2(www.example.com, ca-false, txjsonrpc-test-ca)[tmpkOWcDc-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:56,078 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(www.example.com, ca-false, txjsonrpc-test-ca)[tmpkOWcDc-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:56,355 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:56,355 ClientServerSessionHandler DEBUG   will use profile 6 to handle connection 127.0.0.1 [('127.0.0.1', 47800)->('127.0.0.1', 8443)]
2012-06-25 11:59:56,355 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47800)->('127.0.0.1', 8443)] with profile signed2(www.example.com, ca-true, txjsonrpc-test-ca)[tmpzq20vc-cert.pem]
2012-06-25 11:59:56,362 SSLServerHandler DEBUG   SSL connection accepted, version TLSv1, cipher AES256-SHA-256
2012-06-25 11:59:56,364 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47800)->('127.0.0.1', 8443)] using signed2(www.example.com, ca-true, txjsonrpc-test-ca)[tmpzq20vc-cert.pem] (6/10) resulted in ConnectionAuditResult(signed2(www.example.com, ca-true, txjsonrpc-test-ca)[tmpzq20vc-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:56,379 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(www.example.com, ca-true, txjsonrpc-test-ca)[tmpzq20vc-cert.pem], connected, got 17 octets in 0.0s)
2012-06-25 11:59:56,657 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:56,657 ClientServerSessionHandler DEBUG   will use profile 7 to handle connection 127.0.0.1 [('127.0.0.1', 47801)->('127.0.0.1', 8443)]
2012-06-25 11:59:56,658 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47801)->('127.0.0.1', 8443)] with profile signed2(txjsonrpc-pyserver, ca-none, txjsonrpc-test-ca)[tmpzS7OUa-cert.pem]
2012-06-25 11:59:56,661 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:56,662 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47801)->('127.0.0.1', 8443)] using signed2(txjsonrpc-pyserver, ca-none, txjsonrpc-test-ca)[tmpzS7OUa-cert.pem] (7/10) resulted in ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-none, txjsonrpc-test-ca)[tmpzS7OUa-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:56,680 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-none, txjsonrpc-test-ca)[tmpzS7OUa-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:56,960 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:56,961 ClientServerSessionHandler DEBUG   will use profile 8 to handle connection 127.0.0.1 [('127.0.0.1', 47802)->('127.0.0.1', 8443)]
2012-06-25 11:59:56,962 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47802)->('127.0.0.1', 8443)] with profile signed2(txjsonrpc-pyserver, ca-false, txjsonrpc-test-ca)[tmpegBHnD-cert.pem]
2012-06-25 11:59:56,964 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:56,965 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47802)->('127.0.0.1', 8443)] using signed2(txjsonrpc-pyserver, ca-false, txjsonrpc-test-ca)[tmpegBHnD-cert.pem] (8/10) resulted in ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-false, txjsonrpc-test-ca)[tmpegBHnD-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:56,981 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-false, txjsonrpc-test-ca)[tmpegBHnD-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:57,260 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:57,260 ClientServerSessionHandler DEBUG   will use profile 9 to handle connection 127.0.0.1 [('127.0.0.1', 47803)->('127.0.0.1', 8443)]
2012-06-25 11:59:57,262 SSLServerHandler DEBUG   trying to accept SSL connection 127.0.0.1 [('127.0.0.1', 47803)->('127.0.0.1', 8443)] with profile signed2(txjsonrpc-pyserver, ca-true, txjsonrpc-test-ca)[tmpIiZR0j-cert.pem]
2012-06-25 11:59:57,265 SSLServerHandler DEBUG   SSL accept failed: tlsv1 alert unknown ca
2012-06-25 11:59:57,265 ClientServerSessionHandler DEBUG   handling connection 127.0.0.1 [('127.0.0.1', 47803)->('127.0.0.1', 8443)] using signed2(txjsonrpc-pyserver, ca-true, txjsonrpc-test-ca)[tmpIiZR0j-cert.pem] (9/10) resulted in ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-true, txjsonrpc-test-ca)[tmpIiZR0j-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:57,265 ClientServerSessionHandler DEBUG   last profile for connection 127.0.0.1 [('127.0.0.1', 47803)->('127.0.0.1', 8443)]
2012-06-25 11:59:57,282 BaseClientAuditController DEBUG   got result ConnectionAuditResult(signed2(txjsonrpc-pyserver, ca-true, txjsonrpc-test-ca)[tmpIiZR0j-cert.pem], tlsv1 alert unknown ca)
2012-06-25 11:59:57,282 BaseClientAuditController DEBUG   got result <sslcaudit.core.ConnectionAuditEvent.SessionEndResult object at 0x1376310>
2012-06-25 11:59:57,563 ClientAuditorTCPServer DEBUG   get_original_dst() has thrown an exception: [Errno 92] Protocol not available
2012-06-25 11:59:57,563 BaseClientAuditController DEBUG   exited main loop in run()
2012-06-25 11:59:57,564 ClientServerSessionHandler DEBUG   no unused profiles for connection 127.0.0.1 [('127.0.0.1', 47804)->('127.0.0.1', 8443)], invoking the posttest handler
